### ISSUE TITLE
Mixed Example InnerStruct not populated

### ISSUE THREAD

**Issue by menace102** [rticommunity/rticonnextdds-connector#45] opened 2017-05-18 00:19 UTC
The Mixed Example on master is not populating the innerStruct. It looks like `setNumber()` doesn't work on nested structures. I've verified that both reader.py and Admin Console's Data Viz doesn't pick up those fields.

I'm running Ubuntu 16.04 on Python 2.7.12.

**Comment by gianpiero** [comment] 2017-05-19 17:41
Hello @menace102 

I was able to reproduce the issue. Is not a bug in the Connector per se but in the underling Dynamic Data feature we are using. We identified a fix and it will be available with the next release of RTI Connext. At that point i will update the connector libraries as well. 

Meanwhile, would it be possible for you to test a custom built library? If yes, are you on 32 or 64 bit?

Best,
  Gianpiero

**Comment by gianpiero** [comment] 2017-05-23 22:50
@menace102 ,

The bug (CORE-8044) that caused the issue has to do with setting fields out-of-order. It has been fix and it will be available with the next release (in the July timeframe). I have update the example to make it work but the library that fixes the bug will be available later.

Let me know if you need it before: I can do an engineering build for your architecture.

I will leave this issue open for now and close it when the new libs are uploaded.

**Comment by gianpiero** [comment] 2017-06-29 22:34
Libs are now updated

**Closed by gianpiero** 2017-06-29 22:34 UTC
