### ISSUE TITLE
pip install or local install not working on debian 8 cloud

### ISSUE THREAD

**Issue by itayo** [rticommunity/rticonnextdds-connector#54] opened 2017-10-23 12:54 UTC
It seems that it doesnt really build correctly in debian jessie.

See pip output below

sudo pip install rticonnextdds-connector
Downloading/unpacking rticonnextdds-connector
  Downloading rticonnextdds_connector-0.3.1.tar.gz (56.1MB): 56.1MB downloaded
  Running setup.py (path:/tmp/pip-build-dOrxY4/rticonnextdds-connector/setup.py) egg_info for package rticonnextdds-connector
    
Installing collected packages: rticonnextdds-connector
  Running setup.py install for rticonnextdds-connector
    error: can't copy 'rticonnextdds_connector/iconnextdds-connector/lib/x64Win64VS2013/rtiddsconnector.dll': doesn't exist or not a regular file
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-dOrxY4/rticonnextdds-connector/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4BnzMK-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/rticonnextdds_connector

copying rticonnextdds_connector/rticonnextdds_connector.py -> build/lib.linux-x86_64-2.7/rticonnextdds_connector

copying rticonnextdds_connector/__init__.py -> build/lib.linux-x86_64-2.7/rticonnextdds_connector

creating build/lib.linux-x86_64-2.7/rticonnextdds_connector/iconnextdds-connector

creating build/lib.linux-x86_64-2.7/rticonnextdds_connector/iconnextdds-connector/lib

creating build/lib.linux-x86_64-2.7/rticonnextdds_connector/iconnextdds-connector/lib/x64Win64VS2013

error: can't copy 'rticonnextdds_connector/iconnextdds-connector/lib/x64Win64VS2013/rtiddsconnector.dll': doesn't exist or not a regular file

----------------------------------------
Cleaning up...

**Comment by itayo** [comment] 2017-10-23 12:58
Error exists with pip for both python2.7 and python3.4

**Comment by itayo** [comment] 2017-10-23 12:59
Error also exists when building locally but the copy path is different

**Comment by iblancasa** [comment] 2017-10-26 09:06
Hi @itayo, I was not able to reproduce your issue.

When you say: "Error also exists when building locally but the copy path is different", do you mean that you downloaded the zip from Pypi?
If not, could you download it [from here](https://pypi.python.org/pypi/rticonnextdds_connector/0.3.1) and install it running `python setup.py install`?

**Comment by itayo** [comment] 2017-10-27 09:35
Unfortenly same problem without virtualenv
```
op@63c6156b6af5 ~/a $ md5sum rticonnextdds_connector-0.3.1.tar.gz 
addde579a23541edcf0d3508a7b20682  rticonnextdds_connector-0.3.1.tar.gz
op@63c6156b6af5 ~/a $ tar -xf rticonnextdds_connector-0.3.1.tar.gz 
op@63c6156b6af5 ~/a $ cd rticonnextdds_connector-0.3.1
op@63c6156b6af5 ~/a/rticonnextdds_connector-0.3.1 $ ls
PKG-INFO  README.rst  lib  rticonnextdds_connector  rticonnextdds_connector.egg-info  setup.cfg  setup.py
op@63c6156b6af5 ~/a/rticonnextdds_connector-0.3.1 $ pyt^C
op@63c6156b6af5 ~/a/rticonnextdds_connector-0.3.1 $ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing rticonnextdds_connector.egg-info/PKG-INFO
writing top-level names to rticonnextdds_connector.egg-info/top_level.txt
writing dependency_links to rticonnextdds_connector.egg-info/dependency_links.txt
reading manifest file 'rticonnextdds_connector.egg-info/SOURCES.txt'
writing manifest file 'rticonnextdds_connector.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/rticonnextdds_connector
copying rticonnextdds_connector/rticonnextdds_connector.py -> build/lib.linux-x86_64-2.7/rticonnextdds_connector
copying rticonnextdds_connector/__init__.py -> build/lib.linux-x86_64-2.7/rticonnextdds_connector
creating build/lib.linux-x86_64-2.7/rticonnextdds_connector/_connector-0.3.1
creating build/lib.linux-x86_64-2.7/rticonnextdds_connector/_connector-0.3.1/lib
creating build/lib.linux-x86_64-2.7/rticonnextdds_connector/_connector-0.3.1/lib/x64Win64VS2013
error: can't copy 'rticonnextdds_connector/_connector-0.3.1/lib/x64Win64VS2013/rtiddsconnector.dll': doesn't exist or not a regular file
op@63c6156b6af5 ~/a/rticonnextdds_connector-0.3.1 $ 
```
Same issue even with virtualenv.

**Comment by spiderkeys** [comment] 2017-12-12 22:30
Also seeing this problem on a Raspberry Pi running Debian 8.

### On an Ubuntu 16.04 desktop:
- python v3.5.2
- pip 9.0.1 from /usr/local/lib/python3.5/dist-packages

```bash
spiderkeys@spiderlair:~/workspace/rticonnextdds-connector$ sudo -H pip3 install rticonnextdds-connector
Collecting rticonnextdds-connector
  Downloading rticonnextdds_connector-0.3.1.tar.gz (56.1MB)
    100% |████████████████████████████████| 56.1MB 40kB/s
Building wheels for collected packages: rticonnextdds-connector
  Running setup.py bdist_wheel for rticonnextdds-connector ... done
  Stored in directory: /root/.cache/pip/wheels/db/fc/54/39131240a00dd8a5a038dac31d3bb862fcf891598f582f5fba
Successfully built rticonnextdds-connector
Installing collected packages: rticonnextdds-connector
Successfully installed rticonnextdds-connector-0.3.1
```

### On a Debian 8 RPI3:
- python v3.4.2
- pip 9.0.1 from /usr/local/lib/python3.4/dist-packages

```bash
rov@9e3328e-9e3328e:~$ sudo -H pip3 install rticonnextdds-connector
Collecting rticonnextdds-connector
  Using cached rticonnextdds_connector-0.3.1.tar.gz
Installing collected packages: rticonnextdds-connector
  Running setup.py install for rticonnextdds-connector ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-i105e914/rticonnextdds-connector/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-v5bpzq_0-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/rticonnextdds_connector
    copying rticonnextdds_connector/rticonnextdds_connector.py -> build/lib/rticonnextdds_connector
    copying rticonnextdds_connector/__init__.py -> build/lib/rticonnextdds_connector
    creating build/lib/rticonnextdds_connector/rticonnextdds-connector
    creating build/lib/rticonnextdds_connector/rticonnextdds-connector/lib
    creating build/lib/rticonnextdds_connector/rticonnextdds-connector/lib/armv6vfphLinux3.xgcc4.7.2
    error: can't copy 'rticonnextdds_connector/rticonnextdds-connector/lib/armv6vfphLinux3.xgcc4.7.2/librtiddsconnector.so': doesn't exist or not a regular file
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-i105e914/rticonnextdds-connector/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-v5bpzq_0-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-i105e914/rticonnextdds-connector/
```

I am successfully able to install the package by cloning the repo and using "python setup.py install", but with one caveat: The git repo must be cloned to "rticonnextdds_connector" not "rticonnextdds-connector". Mind the hyphen, as the repo name uses the hyphen.

**Comment by spiderkeys** [comment] 2017-12-12 22:59
More errors. Though my above fix of directly cloning the repo allows for a direct install, it is not possible to import the module:

```sh
root@9e3328e-9e3328e:/home/rov# python3
Python 3.4.2 (default, Oct  8 2014, 14:38:51) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rticonnextdds_connector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/rticonnextdds_connector-0.3.1-py3.4.egg/rticonnextdds_connector/__init__.py", line 1, in <module>
    from .rticonnextdds_connector import *
ImportError: No module named 'rticonnextdds_connector.rticonnextdds_connector'
```
I noticed that the install on my desktop used a wheel and the RPI3 install did not, so I pip installed wheel on the RPI and tried the download again:

```sh
root@9e3328e-9e3328e:/home/rov# pip3 install rticonnextdds-connector
Collecting rticonnextdds-connector
  Using cached rticonnextdds_connector-0.3.1.tar.gz
Building wheels for collected packages: rticonnextdds-connector
  Running setup.py bdist_wheel for rticonnextdds-connector ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6z1byrb1/rticonnextdds-connector/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpi5gpl0pcpip-wheel- --python-tag cp34:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/rticonnextdds_connector
  copying rticonnextdds_connector/rticonnextdds_connector.py -> build/lib/rticonnextdds_connector
  copying rticonnextdds_connector/__init__.py -> build/lib/rticonnextdds_connector
  creating build/lib/rticonnextdds_connector/rticonnextdds-connector
  creating build/lib/rticonnextdds_connector/rticonnextdds-connector/lib
  creating build/lib/rticonnextdds_connector/rticonnextdds-connector/lib/armv6vfphLinux3.xgcc4.7.2
  error: can't copy 'rticonnextdds_connector/rticonnextdds-connector/lib/armv6vfphLinux3.xgcc4.7.2/librtiddsconnector.so': doesn't exist or not a regular file
  
  ----------------------------------------
  Failed building wheel for rticonnextdds-connector
  Running setup.py clean for rticonnextdds-connector
Failed to build rticonnextdds-connector
Installing collected packages: rticonnextdds-connector
  Running setup.py install for rticonnextdds-connector ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6z1byrb1/rticonnextdds-connector/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bmmbg27h-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/rticonnextdds_connector
    copying rticonnextdds_connector/rticonnextdds_connector.py -> build/lib/rticonnextdds_connector
    copying rticonnextdds_connector/__init__.py -> build/lib/rticonnextdds_connector
    creating build/lib/rticonnextdds_connector/rticonnextdds-connector
    creating build/lib/rticonnextdds_connector/rticonnextdds-connector/lib
    creating build/lib/rticonnextdds_connector/rticonnextdds-connector/lib/armv6vfphLinux3.xgcc4.7.2
    error: can't copy 'rticonnextdds_connector/rticonnextdds-connector/lib/armv6vfphLinux3.xgcc4.7.2/librtiddsconnector.so': doesn't exist or not a regular file
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6z1byrb1/rticonnextdds-connector/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bmmbg27h-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-6z1byrb1/rticonnextdds-connector/
```

Verbose output:
```sh
root@9e3328e-9e3328e:/home/rov# pip3 -v install rticonnextdds-connector
Collecting rticonnextdds-connector
  1 location(s) to search for versions of rticonnextdds-connector:
  * https://pypi.python.org/simple/rticonnextdds-connector/
  Getting page https://pypi.python.org/simple/rticonnextdds-connector/
  Looking up "https://pypi.python.org/simple/rticonnextdds-connector/" in the cache
  Current age based on date: 518
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 518
  Analyzing links from page https://pypi.python.org/simple/rticonnextdds-connector/
    Found link https://pypi.python.org/packages/b6/58/c082a3f124289913a3b8e1b0b7c4f7f5b0f741f1e9dd9de42609bde0264e/rticonnextdds_connector-0.2.1.tar.gz#md5=4234d9a961f5076d232b10e963770136 (from https://pypi.python.org/simple/rticonnextdds-connector/), version: 0.2.1
    Found link https://pypi.python.org/packages/ec/60/276d3a5c8a272bccf46ade7fb92f96623257d8a67005ec207b98f5e9c20d/rticonnextdds_connector-0.3.0.tar.gz#md5=8129a229a0e6141beef77b365ce1b2d2 (from https://pypi.python.org/simple/rticonnextdds-connector/), version: 0.3.0
    Found link https://pypi.python.org/packages/f5/99/18c8a0b716f8305b53aaa7c3078b7929ae8e3ecadd684396e0c65f87700a/rticonnextdds_connector-0.3.1.tar.gz#md5=addde579a23541edcf0d3508a7b20682 (from https://pypi.python.org/simple/rticonnextdds-connector/), version: 0.3.1
  Using version 0.3.1 (newest of versions: 0.2.1, 0.3.0, 0.3.1)
  Looking up "https://pypi.python.org/packages/f5/99/18c8a0b716f8305b53aaa7c3078b7929ae8e3ecadd684396e0c65f87700a/rticonnextdds_connector-0.3.1.tar.gz" in the cache
  Current age based on date: 2332
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 2332
  Using cached rticonnextdds_connector-0.3.1.tar.gz
  Downloading from URL https://pypi.python.org/packages/f5/99/18c8a0b716f8305b53aaa7c3078b7929ae8e3ecadd684396e0c65f87700a/rticonnextdds_connector-0.3.1.tar.gz#md5=addde579a23541edcf0d3508a7b20682 (from https://pypi.python.org/simple/rticonnextdds-connector/)
  Running setup.py (path:/tmp/pip-build-6mqxp2dz/rticonnextdds-connector/setup.py) egg_info for package rticonnextdds-connector
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/rticonnextdds_connector.egg-info
    writing top-level names to pip-egg-info/rticonnextdds_connector.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/rticonnextdds_connector.egg-info/dependency_links.txt
    writing pip-egg-info/rticonnextdds_connector.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/rticonnextdds_connector.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/rticonnextdds_connector.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/rticonnextdds_connector.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-6mqxp2dz/rticonnextdds-connector has version 0.3.1, which satisfies requirement rticonnextdds-connector from https://pypi.python.org/packages/f5/99/18c8a0b716f8305b53aaa7c3078b7929ae8e3ecadd684396e0c65f87700a/rticonnextdds_connector-0.3.1.tar.gz#md5=addde579a23541edcf0d3508a7b20682
Building wheels for collected packages: rticonnextdds-connector
  Running setup.py bdist_wheel for rticonnextdds-connector ...   Destination directory: /tmp/tmpq7tukb9lpip-wheel-
  Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6mqxp2dz/rticonnextdds-connector/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpq7tukb9lpip-wheel- --python-tag cp34
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/rticonnextdds_connector
  copying rticonnextdds_connector/rticonnextdds_connector.py -> build/lib/rticonnextdds_connector
  copying rticonnextdds_connector/__init__.py -> build/lib/rticonnextdds_connector
  creating build/lib/rticonnextdds_connector/rticonnextdds-connector
  creating build/lib/rticonnextdds_connector/rticonnextdds-connector/lib
  creating build/lib/rticonnextdds_connector/rticonnextdds-connector/lib/armv6vfphLinux3.xgcc4.7.2
  error: can't copy 'rticonnextdds_connector/rticonnextdds-connector/lib/armv6vfphLinux3.xgcc4.7.2/librtiddsconnector.so': doesn't exist or not a regular file
error
  Failed building wheel for rticonnextdds-connector
  Running setup.py clean for rticonnextdds-connector
  Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6mqxp2dz/rticonnextdds-connector/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all
  running clean
  removing 'build/lib' (and everything under it)
  'build/bdist.linux-armv7l' does not exist -- can't clean it
  'build/scripts-3.4' does not exist -- can't clean it
  removing 'build'
Failed to build rticonnextdds-connector
Installing collected packages: rticonnextdds-connector
  Running setup.py install for rticonnextdds-connector ...     Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6mqxp2dz/rticonnextdds-connector/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mvwhk89l-record/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/rticonnextdds_connector
    copying rticonnextdds_connector/rticonnextdds_connector.py -> build/lib/rticonnextdds_connector
    copying rticonnextdds_connector/__init__.py -> build/lib/rticonnextdds_connector
    creating build/lib/rticonnextdds_connector/rticonnextdds-connector
    creating build/lib/rticonnextdds_connector/rticonnextdds-connector/lib
    creating build/lib/rticonnextdds_connector/rticonnextdds-connector/lib/armv6vfphLinux3.xgcc4.7.2
    error: can't copy 'rticonnextdds_connector/rticonnextdds-connector/lib/armv6vfphLinux3.xgcc4.7.2/librtiddsconnector.so': doesn't exist or not a regular file
error
Cleaning up...
  Removing source in /tmp/pip-build-6mqxp2dz/rticonnextdds-connector
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6mqxp2dz/rticonnextdds-connector/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mvwhk89l-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-6mqxp2dz/rticonnextdds-connector/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.4/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/local/lib/python3.4/dist-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6mqxp2dz/rticonnextdds-connector/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mvwhk89l-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-6mqxp2dz/rticonnextdds-connector/
```

**Comment by spiderkeys** [comment] 2017-12-12 23:05
Found a working install method:
- Clone locally with git
- pip3 install -e ./rticonnextdds-connector/

**Comment by spiderkeys** [comment] 2017-12-13 09:22
Not sure what exactly the ultimate root cause is, but the issue can be clearly seen in the line:
```
error: can't copy 'rticonnextdds_connector/rticonnextdds-connector/lib/armv6vfphLinux3.xgcc4.7.2/librtiddsconnector.so': doesn't exist or not a regular file
```
For some reason the lib file paths don't get resolved correctly during the install process on the RPI3, but do on my x86_64 machine. I believe I have fixed the issue in PR #58 by switching setup.py to use data_files instead of package_data. This results in proper, working results on both platforms.

**Comment by spiderkeys** [comment] 2017-12-13 09:43
There still seems to be an issue with my fix, depending on how you install the package. I have to admit, I'm still learning how the Python dist tools work.

At the least, I am seeing success on both x86_64 and armhf using the following approach:
```sh
wget https://github.com/spiderkeys/rticonnextdds-connector/archive/fix-rpi3.tar.gz \
&& tar -xvf fix-rpi3.tar.gz \
&& pushd rticonnextdds-connector-fix-rpi3 \
&& python3 setup.py install \
&& popd \
&& rm fix-rpi3.tar.gz && rm -rf ./rticonnextdds-connector-fix-rpi3
```

Import test:
```sh
root@9e3328e-9e3328e:/home/rov# python3
Python 3.4.2 (default, Oct  8 2014, 14:38:51) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rticonnextdds_connector
>>> print( rticonnextdds_connector.__file__ )
/usr/local/lib/python3.4/dist-packages/rticonnextdds_connector-0.3.1-py3.4.egg/rticonnextdds_connector/__init__.py
```

**Comment by gianpiero** [comment] 2018-02-15 21:27
I was not able to reproduce this issue. pip2 and pip3 install works just fine. I am closing the issue but if you can help us reproduce the issue we will be happy to re-open it

**Closed by gianpiero** 2018-02-15 21:27 UTC
