### ISSUE TITLE
how to set the max_objects_per_thread in nodejs connector? (Depends on CORE-8126)

### ISSUE THREAD

**Issue by shixukai** [rticommunity/rticonnextdds-connector#59] opened 2018-01-19 08:58 UTC
Or how to set max_objects_per_thread someway in xml config.

here is the log

`[CREATE Participant]REDAWorkerFactory_createObjectPerWorker:!create objectPerWorker: worker factory's max. storage count reached (you may need to increase resource_limits.max_objects_per_thread value)
[CREATE Participant]REDAWorkerFactory_createObjectPerWorker:!create objectPerWorker: worker factory's max. storage count reached (you may need to increase resource_limits.max_objects_per_thread value)`

But I can't find a way the increase the max_objects_per_thread.  I'd be very grateful if someone can help me.

**Comment by gianpiero** [comment] 2018-01-19 22:08
Hello, 

Usually you can change QoS in the XML file. Unfortunately there is a bug in the DDS library (CORE-8126) that connector uses that prevent an application to set max_objects_per_thread using XML. 

Somebody else run into this error and come up with a workaround. You can see the full conversation here: https://community.rti.com/forum-topic/solved-how-change-maxobjectsperthread-rticonnextddsconnector

Best,
  Gianpiero

**Comment by shixukai** [comment] 2018-01-20 04:38
Thanks for your help!
But after build the addon from the gist rep and run it success, the problem is still here !

```
[CREATE Participant]REDAWorkerFactory_createObjectPerWorker:!create objectPerWorker: worker factory's max. storage count reached (you may need to increase resource_limits.max_objects_per_thread value)
[CREATE Participant]REDAWorkerFactory_createObjectPerWorker:!create objectPerWorker: worker factory's max. storage count reached (you may need to increase resource_limits.max_objects_per_thread value)
[CREATE Participant]PRESPsService_new:!create worker-specific object
[CREATE Participant]DDS_DomainParticipantService_initialize:!create publish/subscribe service (participant_index collision?)
[CREATE Participant]DDS_DomainParticipant_createI:!initialize publish/subscribe service
[CREATE Participant]DDS_DomainParticipantDatabase_prefinalize:!database shutdown timeout
[CREATE Participant]RTIEventActiveDatabase_delete:!precondition
[CREATE Participant]DDS_DomainParticipantDatabase_finalize:!delete database
[CREATE Participant]RTIOsapiSemaphore_delete:!delete mutex
[CREATE Participant]DDS_DomainParticipantFactory_create_participant_disabledI:!create participant
```



I check the 'max_objects_per_thread' is changed success:

![2__npm_run_start_server_dev__ssh_](https://user-images.githubusercontent.com/12314563/35179861-cbf4323e-fddd-11e7-841b-78a15576eee0.png)

Is there any other reasons causes the problem?
I try it on Ubuntu 16.04.

**Comment by gianpiero** [comment] 2018-01-22 19:53
Hello, 

mmh this is weird! I suspect that is not an issue related to connector. Can you try to load the same XML using the C api? Do you get the same error? 

Best,
  Gianpiero

**Comment by gianpiero** [comment] 2018-02-15 00:45
Hello,

I am closing this thread because a solution to a similar issue is posted above and I could not reproduce the new one

**Closed by gianpiero** 2018-02-15 00:45 UTC
