### ISSUE TITLE
Memory Leak when using dictionary

### ISSUE THREAD

**Issue by wengjjpaul** [rticommunity/rticonnextdds-connector#42] opened 2017-02-23 06:06 UTC
I encounter memory leak when using samples.getDictionary(j) for data with large sequences of numbers. Any idea?

**Comment by gianpiero** [comment] 2017-02-24 17:48
Hello,

could u provide a simple reproducer so i can instrument and check where the leak is coming from?

Best

**Comment by gianpiero** [comment] 2017-08-04 22:54
I am closing this because I was not able to reproduce it. If you can provide a reproducer,  feel free to reopen it.

Thanks

**Closed by gianpiero** 2017-08-04 22:54 UTC

**Comment by gianpiero** [comment] 2017-10-02 20:44
Hello,

We were able to reproduce the issue. Please follow developments in #53
